Different activation function implementation

In [1]:
import numpy as np

ReLU Activation Function

In [2]:
inputs = [0,2,-1,5,8,12,-79,-5875,1254]

class Activation_ReLU:
    def forward(self,inputs):
        self.output = np.maximum(0,inputs)

In [3]:
activation_relu=Activation_ReLU()

In [5]:
activation_relu.forward(inputs)
print(activation_relu.output)

[   0    2    0    5    8   12    0    0 1254]


Softmax Activation Function

In [6]:
class Activation_softmax:
    def forward(self,inputs):
        exp_values=np.exp(inputs-np.max(inputs,axis=1,keepdims=True))
        prob=exp_values/np.sum(exp_values,axis=1,keepdims=True)
        self.output=prob

In [7]:
inputs1=[[1,2,3,2.5],
         [2.0,-54.0,-3.5,7],
         [-1.5,2.7,3.3,-0.8]]
activation_softmax=Activation_softmax()
activation_softmax.forward(inputs1)

In [8]:
print(activation_softmax.output)

[[6.41476854e-02 1.74371488e-01 4.73990846e-01 2.87489981e-01]
 [6.69266787e-03 3.19969282e-27 2.73514039e-05 9.93279981e-01]
 [5.22983828e-03 3.48758727e-01 6.35479834e-01 1.05316010e-02]]


Sigmoid activation function

In [9]:
class Activation_sigmoid:
    def forward(self, inputs):
        self.output = (1 / (1 + np.exp(-inputs))) 

In [10]:
activation_sigmoid=Activation_sigmoid()

In [11]:
inputs2=np.array([-7,2,3.5,5,8.9,-78])

In [12]:
activation_sigmoid.forward(inputs2)
print(activation_sigmoid.output)

[9.11051194e-04 8.80797078e-01 9.70687769e-01 9.93307149e-01
 9.99863630e-01 1.33361482e-34]


Linear Activation function

In [13]:
class Activation_Linear:
    def forward(self,inputs):
        self.output=inputs

In [14]:
inputs3=[-9,5,7,-16]
activation_linear=Activation_Linear()

In [15]:
activation_linear.forward(inputs3)
print(activation_linear.output)

[-9, 5, 7, -16]
