In [1]:
import numpy as np


In [2]:
import numpy as np
import matplotlib.pyplot as plt

def create_spiral_data(points_per_class=100, num_classes=2, noise=0.5):
    X = []
    y = []
    for class_number in range(num_classes):
        ix = range(points_per_class * class_number, points_per_class * (class_number + 1))
        r = np.linspace(0.0, 1, points_per_class)  # radius
        t = np.linspace(class_number * 4, (class_number + 1) * 4, points_per_class) + np.random.randn(points_per_class) * noise  # theta
        x1 = r * np.sin(t * 2.5)
        x2 = r * np.cos(t * 2.5)
        X.append(np.c_[x1, x2])
        y.append(np.full(points_per_class, class_number))
    
    X = np.concatenate(X)
    y = np.concatenate(y)
    return X, y



In [5]:
class Dense_Layer:
    def __init__(self,n_inputs,n_neurons):
        self.weights=0.01*np.random.randn(n_inputs,n_neurons)
        self.biases=np.zeros((1,n_neurons))
    
    def forward(self,n_inputs):
        self.outputs=np.dot(n_inputs,self.weights)+self.biases
        
x,y=create_spiral_data(points_per_class=100, num_classes=3)    

dense1=Dense_Layer(2,3)

dense1.forward(x)

print(dense1.outputs[:7])


[[ 0.00000000e+00  0.00000000e+00  0.00000000e+00]
 [ 8.61017375e-05  7.34465049e-05 -1.09171937e-04]
 [ 1.73438898e-04  1.03664036e-04 -2.08250219e-04]
 [ 7.99728316e-05 -1.68528390e-04 -3.90630892e-05]
 [ 3.04395882e-04  3.67908754e-04 -4.14460136e-04]
 [ 2.90587592e-04 -8.94067337e-05 -2.79637850e-04]
 [ 1.13767717e-04  5.40521670e-04 -2.61022222e-04]]


In [7]:
# Implementing RelU

inputs=[0,2,-1,3.3,-2.7,1.1,2.2,-100]

class activation_relu:
    def forward(self,input):
        output=np.maximum(0,inputs)

In [8]:
class activation_softmax:
    def forward(self,input):
        exp_val=np.exp(input-np.max(input,axis=1,keepdims=True))
        
        probabilites=exp_val/np.sum(exp_val,axis=1,keepdims=True)
        
        self.output= probabilities